=== javier301/lenguaje-d-emarcas/XML/Practica1/ejercicio2.dtd
<!ELEMENT factura (emisor,cliente,detalle)>
   <!ATTLIST factura numero CDATA #REQUIRED>
   <!ATTLIST factura fecha CDATA #REQUIRED>
<!ELEMENT emisor (nombre,cif,telefono)>
<!ELEMENT cliente (nombre,cif,telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT detalle (linea+)>
    <!ATTLIST detalle importe CDATA #REQUIRED>
<!ELEMENT linea (descripcion,cantidad,oferta?,pvp)>
    <!ATTLIST linea codigo_articulo ID #REQUIRED>
    <!ATTLIST linea tipo (Libro|DVD|Varios) #IMPLIED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT pvp (#PCDATA)>
<!ELEMENT oferta EMPTY>

=== javier301/lenguaje-d-emarcas/XML/Practica1/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "ejercicio2.dtd">


<factura numero="27" fecha="18/12/2013">
<emisor>
<nombre>libreria perez</nombre>
<cif>44555666B</cif>
<telefono>777888999</telefono>
</emisor>
<cliente>
<nombre>biblioteca txanterea</nombre>
<cif>33111222A</cif>
<telefono>333999444</telefono>
</cliente>
<detalle importe="300">
 <linea codigo_articulo="AW7" tipo="Libro">
         <descripcion>Analítica Web 2.0</descripcion>
         <cantidad>1</cantidad>
         <oferta></oferta>
         <pvp>25</pvp>
      </linea>
      <linea codigo_articulo="CP5" tipo="DVD">
         <descripcion>Curso de HTML</descripcion>
         <cantidad>2</cantidad>
         <pvp>30</pvp>
      </linea>
</detalle>
</factura>
