<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria [
<!ELEMENT libreria (libro)+>
<!ELEMENT libro (titulo, autor+, ISBN?, paginas, precio)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
]>
<libreria>
	<libro>
		<titulo>Lenguaje de marcas</titulo>
		<autor>Autor1</autor>
		<autor>Autor2</autor>
		<ISBN> </ISBN>
		<paginas>158</paginas>
		<precio>15</precio>
	</libro>
	<libro>
		<titulo>XML</titulo>
		<autor>Autor1</autor>
		<ISBN> </ISBN>
		<paginas>278</paginas>
		<precio>25</precio>
	</libro>
</libreria>